name: Create git badges

on:
  workflow_dispatch: ~
  release:
    types: [published]


env:
  GIST_TOKEN: ${{ secrets.GIST_SECRET }}
  GIST_ID: cbc0fc3d1258e0bc92c749fb5fbc0860

jobs:
  git-badges:
    name: Git Badges
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo with all history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Output git info
        id: git_info
        run: |
          function format_size { echo $(numfmt --to iec --suffix B $1); }
          function format_number { LC_ALL=en_US.UTF-8 printf "%'d\n" $1; }
          echo "file_count=$(format_number $(git ls-files | wc -l))" >> $GITHUB_OUTPUT
          echo "last_commit_date=$(git log -1 --format=%cd)" >> $GITHUB_OUTPUT
          echo "latest_release=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          echo "commits_to_main=$(format_number $(git rev-list --count main))" >> $GITHUB_OUTPUT
          git gc
          echo "size=$(format_size $(($(git count-objects -v | grep 'size-pack: ' | sed 's/size-pack: //g' | tr -d '\n') * 1024)))" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create git-size badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: git-size.json
          label: size
          message: ${{ steps.git_info.outputs.size }}
          namedLogo: git
          color: f1502f

      - name: Create git-file-count badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: git-file-count.json
          label: files
          message: ${{ steps.git_info.outputs.file_count }}
          namedLogo: git
          color: f1502f

      - name: Create git-last-commit badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: git-last-commit-date.json
          label: last commit
          message: ${{ steps.git_info.outputs.last_commit_date }}
          namedLogo: git
          color: f1502f
    
      - name: Create git-latest-release badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: git-latest-release.json
          label: latest release
          message: ${{ steps.git_info.outputs.latest_release }}
          namedLogo: git
          color: f1502f

      - name: Create git-commits-to-main badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ env.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: git-commits-to-main.json
          label: commits to main
          message: ${{ steps.git_info.outputs.commits_to_main }}
          namedLogo: git
          color: f1502f
