name: Some tests

on:
  workflow_dispatch: ~
  
jobs:
  tests:
    name: Run some tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Get Package.Json
        id: json_properties
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "package.json"
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.json_properties.outputs.engines.node }}
          
      - name: Create MariaDB container
        uses: YakkaDev/mariadb-actions@v1.1.0
        with:
          version: '10.6.15'
          database: 'TEST'
          root-pass: '123123'
          user: 'testuser'
          password: '123321'
          character: 'utf8mb4'
          
      - name: Build package
        run: |
          npm install
          npm run test